[package]
name = "codewars"
version = "0.1.0"
authors = ["Thomas Buß <thomas.buss@codecentric.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]